### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by TobiasKlosek** [aidenlx/marginnote-companion#3]
Hello, 

i would like to try this plugin but it seems it does not work on iPad?
It wont let me activate this plugin in the plugin view.

**Comment by aidenlx** [comment]
Yes, it is intentional since I haven't figure a way to inject handlers to paste events on mobile (CodeMirror 6).

**Comment by TobiasKlosek** [comment]
Okay, will this be a long-term issue? Since i do not use MacOS but just an iPad for me it wouldnt work.

**Comment by aidenlx** [comment]
Yes, it may take a while. Since paste events in the editor are not exposed to API in obsidian yet, I have to access codemirror directly, which varies significantly between mobile and desktop. Mobile and future WYSIWYG mode use CodeMirror 6, which is known to be more difficult to understand and inject into. I have thought about using the context menu in the editor as a workaround, but it seems to be only exposed to internal links on mobile.

**Comment by TobiasKlosek** [comment]
Thanks for the answer! I can understand if that is not user-friendly or workflow-enhancing but it would be a solid start to simply use the plugin. By now there is no way for iPad users to gain out of your plugin :)

**Comment by aidenlx** [comment]
Now with [v5.0.1](https://github.com/aidenlx/marginnote-companion/releases/tag/0.5.1), you can add commands "Insert MarginNote Data to Active Note" and "Auto Insert MarginNote Data to Active Note" to the mobile toolbar, and assign hotkeys to it if you are using a keyboard.

**Comment by TobiasKlosek** [comment]
Thanks! Can you please share a little example how to use it? Im focusing an Note in MarginNote and activated the Bridge-Symbol and did "Insert MarginNote Data to Active Note" in an Obsidian-Note but nothing happens.

**Comment by aidenlx** [comment]
https://user-images.githubusercontent.com/31102694/133299092-1318676b-f799-4af8-bdb0-2b6099a0eb98.mp4

**Comment by TobiasKlosek** [comment]
Ok, with "Auto Insert MarginNote Data to Active Note" it seems to work! 
Thanks!
